# Auth error codes
AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD"

# Password rules
MIN_PASSWORD_LENGTH = 8
